version: '3'
services:
    db:
        image: postgres:13-alpine
        hostname: postgresql
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGPASSWORD: postgres
            POSTGRES_DB: postgres
            TZ: "Asia/Tokyo"
        volumes:
            # - ./postgresql/data:/var/lib/postgresql/data/
            - timer_preset_volume:/var/lib/postgresql/data/
        restart: always

    # mongo:
    #     image: mongo
    #     restart: always
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: root
    #         MONGO_INITDB_ROOT_PASSWORD: password
    #     ports:
    #         - 27017:27017
    #     volumes:
    #         - ./db:/data/db
    #         - ./configdb:/data/configdb

    app:
        build: ./go
        container_name: go_app
        hostname: go_app
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./go/app:/go/app/
        depends_on:
            - db

    nginx:
        build: ./nginx
        container_name: nginx_container_timer
        hostname: nginx
        environment:
            - TZ=Asia/Tokyo
        ports:
            - "80:80"
        depends_on:
            - app

    frontend:
        build: ./frontend
        container_name: frontend_ultimate_timer
        hostname: frontend
        volumes:
            - ./frontend/ultimate_timer:/app
        tty: true
        environment:
            # enables hot reload
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        ports:
            - "3000:3000"

volumes:
    timer_preset_volume: